import { useState } from 'react'
import { Box, Container } from 'theme-ui'
import { Group, Meta, Guide, Link, Header } from '@carbonplan/components'
import { useBreakpointIndex } from '@theme-ui/match-media'

import ControlPanel from '../components/control-panel'
import ControlPanelDivider from '../components/control-panel-divider'
import { RegionDataDisplay } from '../components/region'

import Layers from '../components/options/layers'
import Years from '../components/options/years'
import Viewer from '../components/viewer'
import RegionalEmissions from '../components/regional-emissions'

const sx = {
  heading: {
    fontFamily: 'heading',
    letterSpacing: 'smallcaps',
    textTransform: 'uppercase',
    fontSize: [2, 2, 2, 3],
    mb: [1, 1, 1, 2],
  },
  description: {
    fontSize: [1, 1, 1, 2],
    pb: [2],
  },
}

const initialLayers = {
  emissions: true,
}

function Index() {
  const [layers, setLayers] = useState(initialLayers)
  const [year, setYear] = useState('2001')
  const [expanded, setExpanded] = useState(false)

  const index = useBreakpointIndex()
  const isMobile = index === 0
  return (
    <>
      <Meta />
      <Container>
        <Guide color='teal' />
      </Container>
      <Box sx={{ position: 'absolute', top: 0, width: '100%', zIndex: 5000 }}>
        <Box
          as='header'
          sx={
            isMobile
              ? {
                  width: '100%',
                  borderStyle: 'solid',
                  borderColor: 'muted',
                  borderWidth: '0px',
                  borderBottomWidth: '1px',
                  position: 'sticky',
                  top: 0,
                  bg: 'background',
                  height: '56px',
                  zIndex: 2000,
                }
              : {}
          }
        >
          <Container>
            <Header
              dimmer={'none'}
              settings={{
                expanded,
                onClick: () => setExpanded((prev) => !prev),
              }}
            />
          </Container>
        </Box>
      </Box>
      <Box
        sx={{
          position: 'absolute',
          top: 0,
          bottom: 0,
          width: '100%',
          left: 0,
        }}
      >
        <Viewer year={year}>
          <Container>
            <ControlPanel
              title='Mapping forest carbon'
              description={
                <span>
                  Read our{' '}
                  <Link href='/blog/climate-trace-release'>blog post</Link>,
                  play with the{' '}
                  <Link onClick={() => setExpanded(true)}>map</Link>
                </span>
              }
              expanded={expanded}
              setExpanded={setExpanded}
            >
              <Group spacing={4}>
                <Box sx={sx.description}>
                  This map shows annual committed emissions from stand-replacing
                  forest disturbance. It's generated by combining year 2000{' '}
                  <Link>aboveground biomass</Link> with{' '}
                  <Link>forest cover change</Link>. It was prepared for the{' '}
                  <Link href='https://climatetrace.org'>Climate TRACE</Link>{' '}
                  project. Read our{' '}
                  <Link href='/blog/climate-trace-release'>blog post</Link> or
                  check out our{' '}
                  <Link href='https://github.com/carbonplan/trace'>
                    GitHub repository
                  </Link>{' '}
                  for more details.
                </Box>
                <ControlPanelDivider />
                <Layers layers={layers} setLayers={setLayers} sx={sx} />
                <ControlPanelDivider />
                <Years year={year} setYear={setYear} sx={sx} />
                {!isMobile && <ControlPanelDivider />}
                {!isMobile && (
                  <RegionDataDisplay sx={sx}>
                    <RegionalEmissions year={year} />
                  </RegionDataDisplay>
                )}
              </Group>
            </ControlPanel>
          </Container>
        </Viewer>
      </Box>
    </>
  )
}

export default Index
